name: 🐛 Bug Report
description: Report a defect or issue in the app.
labels: [bug]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short summary of the issue.
      placeholder: e.g. App crashes when saving a new firearm
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: 1. Go to Add Ammo → 2. Enter data → 3. Tap Save
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: I expected the item to be saved without errors.

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: The app showed a white screen and didn’t save anything.

  - type: input
    id: version
    attributes:
      label: App Version + Build Number
      placeholder: e.g. 1.0.1 (Build 7)
